# Generated by Django 3.1.2 on 2020-12-09 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('data_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_time_series', models.BooleanField(blank=True, null=True)),
                ('has_subject_name', models.BooleanField(blank=True, null=True)),
                ('dc_table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dc_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DataCategory',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('study_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_name', models.CharField(blank=True, max_length=255, null=True)),
                ('study_description', models.TextField(blank=True, null=True)),
                ('is_irb_approved', models.BooleanField(blank=True, null=True)),
                ('institutions_involved', models.TextField(blank=True, null=True)),
                ('study_start_date', models.DateField(blank=True, null=True)),
                ('study_end_date', models.DateField(blank=True, null=True)),
                ('study_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('study_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Study',
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('study_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('study_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('study_group_description', models.TextField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapipeline.study')),
            ],
            options={
                'db_table': 'StudyGroup',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_number', models.CharField(blank=True, max_length=255, null=True)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapipeline.studygroup')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='DataCategoryStudyXref',
            fields=[
                ('dc_study_id', models.AutoField(primary_key=True, serialize=False)),
                ('dc_table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapipeline.datacategory')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapipeline.study')),
            ],
            options={
                'db_table': 'DataCategoryStudyXref',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attr_id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attr_description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapipeline.datacategory')),
            ],
            options={
                'db_table': 'Attribute',
            },
        ),
    ]
