# Generated by Django 3.1.2 on 2020-12-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
