# Generated by Django 3.1.2 on 2020-11-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfiles',
            name='filename',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
