# Generated by Django 3.1.2 on 2020-12-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='Attribute',
        ),
        migrations.AlterModelTable(
            name='datacategory',
            table='DataCategory',
        ),
        migrations.AlterModelTable(
            name='datacategorystudyxref',
            table='DataCategoryStudyXref',
        ),
        migrations.AlterModelTable(
            name='study',
            table='Study',
        ),
        migrations.AlterModelTable(
            name='studygroup',
            table='StudyGroup',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
    ]
