# Generated by Django 3.1.2 on 2020-11-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0002_csvfiles_filename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSVFiles',
            new_name='Document',
        ),
    ]
