# Generated by Django 3.1.2 on 2021-01-19 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_delete_document'),
        ('datapipeline', '0002_datacategory_subject_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacategorystudyxref',
            name='data_category',
        ),
        migrations.RemoveField(
            model_name='datacategorystudyxref',
            name='study',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='study',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='study_group',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='DataCategory',
        ),
        migrations.DeleteModel(
            name='DataCategoryStudyXref',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
        migrations.DeleteModel(
            name='StudyGroup',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
