# Generated by Django 3.1.2 on 2020-11-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0003_auto_20201110_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
