# Generated by Django 3.1.2 on 2021-01-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datapipeline', '0004_attribute_datacategory_datacategorystudyxref_study_studygroup_subject'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='attribute',
        ),
        migrations.AlterModelTable(
            name='datacategory',
            table='datacategory',
        ),
        migrations.AlterModelTable(
            name='datacategorystudyxref',
            table='datacategorystudyxref',
        ),
        migrations.AlterModelTable(
            name='study',
            table='study',
        ),
        migrations.AlterModelTable(
            name='studygroup',
            table='studygroup',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
