# Generated by Django 3.1.2 on 2021-01-19 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datapipeline', '0004_attribute_datacategory_datacategorystudyxref_study_studygroup_subject'),
        ('uploader', '0002_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=250)),
                ('data_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datapipeline.datacategory')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
    ]
