# Generated by Django 3.1.2 on 2021-01-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
